# Generated by Django 5.0.4 on 2024-04-29 21:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_equipment_assigned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date',
            new_name='reserved_from',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserved_to',
            field=models.DateField(default=core.models.get_current_date),
        ),
    ]
