# Generated by Django 5.0.4 on 2024-04-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_date_reservation_reserved_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='cpu',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='gpu',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
